version: '3.9'

services:
  db:
    image: postgres:15
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: app_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: appdb
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]

  tests:
    build: .
    container_name: app_tests
    depends_on:
      - backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: appdb
    command: ["go", "test", "./tests/..."]
